[package]
name = "chunk-server"
version = "0.1.0"
authors = ["zoran <lazarevic.zoki91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-multipart = "0.3"
actix-utils = "2.0.0"
mpart-async = "0.4.2"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "io"] }
serde = { version = "1.0", features = ["derive"] }
futures = "0.3.9"
dirs = "3.0.1"
ccfs-commons = { path = "../ccfs-commons" }
snafu = "0.6.10"
sanitize-filename = "0.3"
uuid = "0.8.1"
pnet = "0.27.2"
