[package]
name = "chunk-server"
version = "0.1.0"
authors = ["zoran <lazarevic.zoki91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
rocket-multipart-form-data = { git = "https://github.com/impero-com/rocket-multipart-form-data", branch = "rocket-0.5" }
dirs = "3.0.1"
reqwest = { version = "0.10.10", features = ["json"] }
ccfs-commons = { path = "../ccfs-commons" }
snafu = "0.6.10"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
default-features = false
features = ["uuid", "json"]
