[package]
name = "metadata-server"
version = "0.1.0"
authors = ["zoran <lazarevic.zoki91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
uuid = { version = "0.7", features = ["v4"] }
lazy_static = "1.4.0"
mut_static = "5.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
ccfs-commons = {path = "../ccfs-commons"}

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["uuid", "json"]