[package]
name = "cli"
version = "0.1.0"
authors = ["zoran <lazarevic.zoki91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8.1", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
structopt = "0.3.21"
reqwest = { version = "0.10.10", features = ["json", "stream"] }
ccfs-commons = { path = "../ccfs-commons" }
snafu = "0.6.10"
slice-group-by = "0.2.6"
futures = "0.3.8"
rand = "0.8.0"
